//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int personaId { get; set; }
        public string personaNombre { get; set; }
        public Nullable<int> personaSexoId { get; set; }
    
        public virtual sexo sexo { get; set; }
    }
}
